version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  neo4j:
    image: 'neo4j:4.4.17'
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: 'neo4j/SomeUselessPassword02'
  postgres:
    image: 'postgres:15.3'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'idk_user'
      POSTGRES_PASSWORD: 'SomeUselessPassword02'
      POSTGRES_DB: 'yasn'