version: '3.7'

services:
  app:
    image: 'regyl/testing-system:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testingsystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=SomeUselessPassword02
      - SERVER_PORT=8090
    ports:
      - '8090:8090'

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SomeUselessPassword02
      - POSTGRES_DB=testingsystem