services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  neo4j:
    image: 'neo4j:4.0.0'
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: 'neo4j/neo4j'